public class Sapatos {
    private Long id;
    private String marca;
    private String modelo;
    private int numero;
    private String cor;
    private String imagem;

    public Sapatos() {}

    public Sapatos(String marca, String modelo, int numero, String cor, String imagem) {
        this.marca = marca;
        this.modelo = modelo;
        this.numero = numero;
        this.cor = cor;
        this.imagem = imagem;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public String getCor() {
        return cor;
    }

    public void setCor(String cor) {
        this.cor = cor;
    }

    public String getImagem() {
        return imagem;
    }

    public void setImagem(String imagem) {
        this.imagem = imagem;
    }
}
